# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(364, 718)
        main.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(main)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(main)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.log = QtWidgets.QTextEdit(main)
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 11, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.to_ev = QtWidgets.QSpinBox(main)
        self.to_ev.setMinimum(-7)
        self.to_ev.setMaximum(7)
        self.to_ev.setObjectName("to_ev")
        self.gridLayout.addWidget(self.to_ev, 4, 2, 1, 1)
        self.bitrate = QtWidgets.QSpinBox(main)
        self.bitrate.setPrefix("")
        self.bitrate.setMinimum(1)
        self.bitrate.setMaximum(120)
        self.bitrate.setProperty("value", 20)
        self.bitrate.setObjectName("bitrate")
        self.gridLayout.addWidget(self.bitrate, 9, 1, 1, 2)
        self.Layout_stream = QtWidgets.QHBoxLayout()
        self.Layout_stream.setObjectName("Layout_stream")
        self.start_preview = QtWidgets.QPushButton(main)
        self.start_preview.setToolTip("")
        self.start_preview.setCheckable(True)
        self.start_preview.setChecked(False)
        self.start_preview.setAutoExclusive(False)
        self.start_preview.setObjectName("start_preview")
        self.Layout_stream.addWidget(self.start_preview)
        self.start_live = QtWidgets.QPushButton(main)
        self.start_live.setCheckable(True)
        self.start_live.setChecked(False)
        self.start_live.setFlat(False)
        self.start_live.setObjectName("start_live")
        self.Layout_stream.addWidget(self.start_live)
        self.gridLayout.addLayout(self.Layout_stream, 5, 0, 1, 3)
        self.from_ev = QtWidgets.QSpinBox(main)
        self.from_ev.setMinimum(-7)
        self.from_ev.setMaximum(7)
        self.from_ev.setObjectName("from_ev")
        self.gridLayout.addWidget(self.from_ev, 4, 1, 1, 1)
        self.rtsp_server = QtWidgets.QLineEdit(main)
        self.rtsp_server.setObjectName("rtsp_server")
        self.gridLayout.addWidget(self.rtsp_server, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(main)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.resolution = QtWidgets.QComboBox(main)
        self.resolution.setEditable(False)
        self.resolution.setObjectName("resolution")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.gridLayout.addWidget(self.resolution, 10, 1, 1, 2)
        self.take_picture = QtWidgets.QPushButton(main)
        self.take_picture.setObjectName("take_picture")
        self.gridLayout.addWidget(self.take_picture, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 1)
        self.camera_ip = QtWidgets.QLineEdit(main)
        self.camera_ip.setObjectName("camera_ip")
        self.gridLayout.addWidget(self.camera_ip, 0, 1, 1, 2)
        self.connect_camera = QtWidgets.QPushButton(main)
        self.connect_camera.setEnabled(True)
        self.connect_camera.setCheckable(True)
        self.connect_camera.setChecked(False)
        self.connect_camera.setObjectName("connect_camera")
        self.gridLayout.addWidget(self.connect_camera, 3, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.live_stiching = QtWidgets.QCheckBox(main)
        self.live_stiching.setObjectName("live_stiching")
        self.horizontalLayout.addWidget(self.live_stiching)
        self.stabilization = QtWidgets.QCheckBox(main)
        self.stabilization.setObjectName("stabilization")
        self.horizontalLayout.addWidget(self.stabilization)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 2, 3)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Insta360 Controller"))
        self.label_4.setText(_translate("main", "Live Bitrate :"))
        self.label_2.setText(_translate("main", "RTSP Server :"))
        self.to_ev.setPrefix(_translate("main", "To EV : "))
        self.bitrate.setToolTip(_translate("main", "1~120Mbps"))
        self.bitrate.setSuffix(_translate("main", "  Mbps"))
        self.start_preview.setText(_translate("main", "Start Preview"))
        self.start_live.setText(_translate("main", "Start  Live"))
        self.from_ev.setPrefix(_translate("main", "From EV : "))
        self.rtsp_server.setText(_translate("main", "rtsp://localhost:8554"))
        self.label.setText(_translate("main", "Camera Adress :"))
        self.resolution.setItemText(0, _translate("main", "3840x2880@30fps"))
        self.resolution.setItemText(1, _translate("main", "3840x2160@60fps"))
        self.resolution.setItemText(2, _translate("main", "3840x2160@30fps"))
        self.resolution.setItemText(3, _translate("main", "3840x1920@60fps"))
        self.resolution.setItemText(4, _translate("main", "3200x2400@30fps"))
        self.resolution.setItemText(5, _translate("main", "1920x1440@30fps"))
        self.resolution.setItemText(6, _translate("main", "1920x1440@120fps"))
        self.take_picture.setText(_translate("main", "Take 360 Picture"))
        self.label_3.setText(_translate("main", "Camera Resolution :"))
        self.camera_ip.setText(_translate("main", "http://192.168.2.139"))
        self.connect_camera.setText(_translate("main", "Connect Camera"))
        self.live_stiching.setToolTip(_translate("main", "Live stiching is force 4k resolution"))
        self.live_stiching.setText(_translate("main", "Live Stiching"))
        self.stabilization.setText(_translate("main", "stabilization"))
